### ISSUE TITLE
Display error in landscape screen mode

### ISSUE THREAD

**Issue by GrizzlyRen** [workspace/bottomsheetdialog-compose#33]
I'm using version 1.2.1 . In landscape mode,dialog will dispay juest display a  part of top, cannot display all

**Comment by workspace** [comment]
@GrizzlyRen you can set BottomSheetBehaviorProperties like this. Is it enough for your requirements?

https://github.com/holixfactory/bottomsheetdialog-compose/assets/7759511/7b50b398-8e0d-4d47-87a5-a5f938c54e1e
