### ISSUE TITLE
Part of bottomSheet hiding behind keyboard

### ISSUE THREAD

**Issue by devnunu** [workspace/bottomsheetdialog-compose#6]
Hi, There was a issue while using library.
If there is an input in the bottomSheet and the keyboard is raised due to focus on the input, the button fixed at the bottom is hidden behind the keyboard. 

The activity is set to adjustResize . I checked to see if there is a way to solve this, but I'm not sure. If this function is not supported, could you add a function to raise the area of ​​the bottomSheet as much as the keyboard area? Thank you.

**Comment by workspace** [comment]
@devnunu Can you give me example code to reproduce?

(Fork this repository -> edit sample -> push -> share your repository and branch🙌)

**Comment by lulumeya** [comment]
@devnunu 
In case of you used bringIntoViewRequester, you can pass a Rect to bringIntoView function which indicates the area should be lifted along. Rect should indicate the area starting from focused component to the component you want to be visible. The behavior you addressing is a very intended behavior while lifting up the keyboard. If the area below focused content have large area, keyboard should cover that area to ensure the visibility of focused component.
